-- Insert renal/nephrology questions for test_id 5c61dbfd-004a-448d-a47a-d764a2710884
-- Run in Supabase SQL Editor or: psql -f supabase/seed_renal_questions.sql

INSERT INTO public.questions (test_id, question_text, option_a, option_b, option_c, option_d, correct_option, rationale, marks, order_index)
VALUES
  ('5c61dbfd-004a-448d-a47a-d764a2710884', 'A patient with chronic renal failure presents with a hemoglobin of 8g/dL. The nurse understands this anemia is primarily due to a deficiency in:', 'Renin', 'Erythropoietin', 'Vitamin D', 'Aldosterone', 'b', 'The kidneys have an endocrine function to produce erythropoietin, which stimulates red blood cell (RBC) production in the bone marrow. Diseased kidneys produce less of this hormone, leading to anemia.', 1, 1),
  ('5c61dbfd-004a-448d-a47a-d764a2710884', 'A nurse is caring for a child diagnosed with Nephrotic Syndrome. Which clinical finding is most consistent with this diagnosis?', 'Cola-colored urine', 'Hypertension and fever', 'Generalized edema (Anasarca)', 'Low serum cholesterol', 'c', 'Nephrotic syndrome is characterized by massive protein loss, which decreases plasma oncotic pressure, leading to fluid movement into interstitial spaces and resulting in generalized edema or anasarca.', 1, 2),
  ('5c61dbfd-004a-448d-a47a-d764a2710884', 'While managing a patient in the oliguric phase of Acute Renal Failure (ARF), the nurse should expect which urine output volume?', 'Less than 100 mL/day', 'Less than 400 mL/day', 'Between 1–1.5 L/day', 'More than 2.5 L/day', 'b', 'Oliguria is defined as a decreased urine output of less than 400 mL in 24 hours and is a hallmark of the maintenance phase of ARF.', 1, 3),
  ('5c61dbfd-004a-448d-a47a-d764a2710884', 'A patient is scheduled for an Intravenous Pyelogram (IVP). Which nursing assessment is the highest priority before the procedure?', 'Assess the patient''s ability to remain still.', 'Monitor for signs of urinary retention.', 'Assess for iodine or contrast dye allergies.', 'Check the patient''s last meal time.', 'c', 'IVP involves the injection of a contrast dye. Assessing for allergies to iodine or contrast is vital to prevent life-threatening anaphylactic reactions.', 1, 4),
  ('5c61dbfd-004a-448d-a47a-d764a2710884', 'A patient with Chronic Kidney Disease (CKD) complains of severe itching (pruritus). The nurse explains this is likely caused by:', 'Accumulation of uremic toxins in the blood.', 'Decreased activation of Vitamin D.', 'Allergic reaction to phosphate binders.', 'Low serum sodium levels.', 'a', 'In renal failure, metabolic waste products (uremia) accumulate in the blood and deposit in the skin, causing significant irritation and itching.', 1, 5),
  ('5c61dbfd-004a-448d-a47a-d764a2710884', 'Which part of the nephron is primarily responsible for the concentration of urine?', 'Glomerulus', 'Proximal Convoluted Tubule (PCT)', 'Distal Convoluted Tubule (DCT)', 'Loop of Henle', 'd', 'The Loop of Henle is the specific part of the renal tubule responsible for the concentration of urine.', 1, 6),
  ('5c61dbfd-004a-448d-a47a-d764a2710884', 'A patient presents with "cola-colored" urine and periorbital edema following a recent throat infection. The nurse suspects:', 'Nephrotic Syndrome', 'Acute Glomerulonephritis (AGN)', 'Cystitis', 'Chronic Renal Failure', 'b', 'AGN often follows a streptococcal throat infection. The "cola-colored" urine (hematuria) and periorbital edema are classic signs of this inflammatory condition.', 1, 7),
  ('5c61dbfd-004a-448d-a47a-d764a2710884', 'A nurse is educating a female patient on preventing recurrent Cystitis. Which instruction should be included?', 'Wear tight-fitting synthetic underwear.', 'Limit fluid intake to 1 liter per day.', 'Wipe from front to back after toileting.', 'Use perfumed soaps for perineal hygiene.', 'c', 'Wiping from front to back prevents the migration of bacteria (like E. coli) from the anal region to the urethra, reducing the risk of ascending infection.', 1, 8),
  ('5c61dbfd-004a-448d-a47a-d764a2710884', 'A patient in the diuretic phase of ARF has a urine output of 3L/day. The nurse''s priority is monitoring for:', 'Fluid overload', 'Dehydration and electrolyte loss', 'Increased blood pressure', 'Uremic frost', 'b', 'During the diuretic phase, the kidneys can produce urine but cannot yet concentrate it, leading to a high risk of massive fluid and electrolyte loss.', 1, 9),
  ('5c61dbfd-004a-448d-a47a-d764a2710884', 'A patient with CKD is prescribed Phosphate Binders. When should the nurse instruct the patient to take this medication?', '1 hour before meals', 'With meals', 'At bedtime', 'Only when the patient has bone pain', 'b', 'Phosphate binders must be taken with food to bind the phosphorus present in the meal and prevent its absorption into the bloodstream.', 1, 10),
  ('5c61dbfd-004a-448d-a47a-d764a2710884', 'Which of the following is a pre-renal cause of Acute Renal Failure?', 'Kidney stones (Calculi)', 'Nephrotoxic drugs like Gentamicin', 'Hypovolemia due to hemorrhage', 'Benign Prostatic Hypertrophy (BPH)', 'c', 'Pre-renal causes are conditions that reduce blood flow to the kidneys, such as hypovolemia, shock, or heart failure.', 1, 11),
  ('5c61dbfd-004a-448d-a47a-d764a2710884', 'A patient with AGN is on a restricted diet. Which of the following should be encouraged to provide energy while sparing protein?', 'High-protein diet', 'High-carbohydrate diet', 'High-potassium foods', 'High-sodium snacks', 'b', 'High carbohydrates provide energy and prevent the body from breaking down protein (catabolism), which would otherwise increase nitrogenous waste.', 1, 12),
  ('5c61dbfd-004a-448d-a47a-d764a2710884', 'A nurse observes foamy urine in a patient with Nephrotic Syndrome. This foaminess is primarily due to:', 'High glucose levels', 'Massive proteinuria', 'Presence of bacteria', 'Concentrated urine', 'b', 'Massive loss of protein in the urine (proteinuria) creates a foamy or frothy appearance.', 1, 13),
  ('5c61dbfd-004a-448d-a47a-d764a2710884', 'Which nursing intervention is essential post-kidney biopsy?', 'Encourage immediate ambulation.', 'Keep the patient on bed rest for 6–8 hours.', 'Administer a dose of diuretics.', 'Restrict all oral fluids.', 'b', 'Post-biopsy patients must remain on bed rest to prevent internal bleeding at the biopsy site.', 1, 14),
  ('5c61dbfd-004a-448d-a47a-d764a2710884', 'A patient presents with "Renal Colic." The nurse identifies this pain as:', 'Dull ache in the suprapubic area.', 'Severe, sharp pain radiating from flank to groin.', 'Burning sensation during voiding.', 'Pain felt only during night urination.', 'b', 'Renal colic is the intense pain caused by kidney stones obstructing the urinary tract.', 1, 15),
  ('5c61dbfd-004a-448d-a47a-d764a2710884', 'Which hormone produced by the kidney is responsible for blood pressure regulation?', 'Erythropoietin', 'Renin', 'Aldosterone', 'Antidiuretic Hormone (ADH)', 'b', 'Renin is an enzyme/hormone produced by the kidneys that regulates blood pressure via the renin-angiotensin system.', 1, 16),
  ('5c61dbfd-004a-448d-a47a-d764a2710884', 'A patient is diagnosed with Reiter''s Syndrome. The nurse recognizes the "triad" of symptoms as:', 'Fever, chills, and flank pain.', 'Arthritis, urethritis, and conjunctivitis.', 'Proteinuria, edema, and hypertension.', 'Dysuria, frequency, and urgency.', 'b', 'Reiter''s Syndrome (Reactive Arthritis) is specifically defined by the triad of joint inflammation, urethral inflammation, and eye inflammation.', 1, 17),
  ('5c61dbfd-004a-448d-a47a-d764a2710884', 'In Chronic Kidney Disease, why are patients advised to avoid NSAIDs like Ibuprofen?', 'They cause excessive sleepiness.', 'They increase the risk of infection.', 'They are nephrotoxic and can worsen renal damage.', 'They interfere with Vitamin D activation.', 'c', 'NSAIDs are nephrotoxic drugs that can further damage already impaired nephrons.', 1, 18);
